### ISSUE TITLE
recover commits

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/css_layout_with_bootstrap#11]
Accidentally removed previous without backing up.

**Comment by jrhorn424** [comment]
Do what?

**Comment by gaand** [comment]
@RealWeeks Would you please explain?  Thanks.

**Comment by Jcornmanhomonoff** [comment]
@gaand unsure what's happening here...

**Comment by jrhorn424** [comment]
@gaand @RealWeeks @Jcornmanhomonoff Reviewing the history, I see what happened here. I'm pretty sure Weeks destroyed our history in the master branch, since I wrote this lesson originally and can't find any commits that contain my original "Golden Layout" discussion (see #32).

I'm closing this. If Weeks can find the commits he lost somewhere in Time Machine or a backup from early 2016, I can perform some `git` surgery. But if not, I'd prefer to get this off our radar.

🔨
